
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('answers').del()
    .then(function () {
      // Inserts seed entries
      return knex('answers').insert([
        {id: 1, id_candidates: 1, id_offers: 1, id_questions: 1, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 2, id_candidates: 1, id_offers: 1, id_questions: 2, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 3, id_candidates: 2, id_offers: 1, id_questions: 1, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 4, id_candidates: 2, id_offers: 1, id_questions: 2, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 5, id_candidates: 3, id_offers: 1, id_questions: 1, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 6, id_candidates: 3, id_offers: 1, id_questions: 2, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},

        {id: 7, id_candidates: 1, id_offers: 2, id_questions: 3, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 8, id_candidates: 1, id_offers: 2, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 9, id_candidates: 2, id_offers: 2, id_questions: 3, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 10, id_candidates: 2, id_offers: 2, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 11, id_candidates: 3, id_offers: 2, id_questions: 3, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 12, id_candidates: 3, id_offers: 2, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},

        {id: 13, id_candidates: 1, id_offers: 3, id_questions: 6, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 14, id_candidates: 1, id_offers: 3, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 15, id_candidates: 2, id_offers: 3, id_questions: 6, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 16, id_candidates: 2, id_offers: 3, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 17, id_candidates: 3, id_offers: 3, id_questions: 6, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
        {id: 18, id_candidates: 3, id_offers: 3, id_questions: 5, text: 'Quisque eget felis eget magna porttitor convallis quis congue eros. Vestibulum iaculis quis leo nec porttitor. Etiam in ligula et nisl mattis eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu nibh a diam ullamcorper fermentum. Nunc eu metus congue, varius leo non, tristique ante. Aenean convallis orci at facilisis ullamcorper. Sed tincidunt tellus eu volutpat tincidunt.'},
      ]);
    });
};
